Algoritmo "input_visualG"

Var
    nome: caractere
    idade: inteiro
    salario_1, salario_2: real
    
Inicio
    escreva("DIgite o seu nome: ")
    leia(nome)
    escreva("Digite a sua idade:")
    leia(idade)
    escreval("Digite quanto voce ganhou nos dois ultimos meses:")
    leia(salario_1,salario_2)
    escreval("Dados digitados")
    escreval("Nome: ", nome)
    escreval("Idade: ", nome)
    escreval("Salario: ", salario_1)
    escreval("Salario: ", salario_2)
Fimalgoritmo